FROM python:3.11-slim
WORKDIR /app
COPY requirements-api.txt .
RUN pip install --no-cache-dir -r requirements-api.txt
COPY src/__init__.py src/__init__.py
COPY src/api.py src/api.py
COPY models/sentiment_model_char.pkl models/sentiment_model_char.pkl
COPY models/tfidf_vectorizer_char.pkl models/tfidf_vectorizer_char.pkl
EXPOSE 8000
CMD ["uvicorn", "src.api:app", "--host", "0.0.0.0", "--port", "8000"]